# Generated by Django 4.2.23 on 2025-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="youtube_profile",
            field=models.URLField(blank=True, null=True),
        ),
    ]
