# Generated by Django 4.2.23 on 2025-10-05 19:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_youtube_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
