# Generated by Django 4.2.23 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_profile_email_host_profile_email_host_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="other_email_host",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
