# Generated by Django 4.2.23 on 2026-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="table_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
