# Generated by Django 4.2.23 on 2026-02-04 13:34

from django.db import migrations


def create_schemas(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    tables = [
        "venues_venue",
        "venues_venuecontact",
        "festivals_festival",
        "festivals_festivalcontact",
        "residencies_residency",
        "residencies_residencycontact",
    ]

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE SCHEMA IF NOT EXISTS template")

        for table in tables:
            cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS template.{table} 
                (LIKE public.{table} INCLUDING ALL)
            """)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_profile_date_format_profile_table_size"),
        ("venues", "0006_venue_deleted_at_venuecontact_deleted_at"),
        ("festivals", "0014_festival_deleted_at_festivalcontact_deleted_at"),
        ("residencies", "0006_residency_deleted_at_residencycontact_deleted_at"),
    ]

    operations = [
        migrations.RunPython(create_schemas, reverse_code=migrations.RunPython.noop),
    ]
