# Generated by Django 6.0.3 on 2026-03-12 14:40

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_profile_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_oauth_access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_oauth_refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_oauth_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="outlook_oauth_access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="outlook_oauth_refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="outlook_oauth_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
