# Generated by Django 4.2.23 on 2025-08-26 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.AddField(
            model_name='application',
            name='application_method',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('FORM', 'Form'), ('INVITATION_ONLY', 'Invitation only'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='EMAIL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attachments_received',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attachments_sent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contract_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='performance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='response_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPLIED', 'Applied'), ('IN_DISCUSSION', 'In discussion'), ('REJECTED', 'Rejected'), ('IGNORED', 'Ignored'), ('ACCEPTED', 'Accepted'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('OTHER', 'Other')], default='NOT_APPLIED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
