# Generated by Django 4.2.23 on 2025-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0007_alter_application_application_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
