# Generated by Django 4.2.23 on 2025-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0011_alter_festival_application_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARRED", "Starred"),
                    ("WARNING", "Warning"),
                    ("INACTIVE", "Inactive"),
                    ("WATCH", "Watch"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
