# Generated by Django 4.2.23 on 2025-10-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0012_festival_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STAR", "Star"),
                    ("WARNING", "Warning"),
                    ("INACTIVE", "Inactive"),
                    ("WATCH", "Watch"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
