# Tells nginx where to ask for DNS lookups. 127.0.0.11 is docker's built in DNS server
# Knows the current IP of every container by name
resolver 127.0.0.11 valid=5m;

server {
    listen 80;
    server_name clapp.ovh;

    set $django django:8000;
    set $nextjs next:3000;

    # Static files
    location /static/ {
        alias /app/staticfiles/;
    }

    # Media files
    location /media/ {
        alias /app/media/;
    }

    location /_next/static/ {
        # proxy pass: where the request gets forwarded
        proxy_pass http://$nextjs;
        proxy_set_header Host $host;
    }

    location /_next/image {
        proxy_pass http://$nextjs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://$django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health/ {
        proxy_pass http://$django;
        proxy_set_header Host $host;
    }

    # Next.js frontend (everything else)
    location / {
        proxy_pass http://$nextjs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Next.js hot reload / websocket (for dev)
    location /_next/webpack-hmr {
        proxy_pass http://$nextjs;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}