# Generated by Django 4.2.23 on 2026-01-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugreport",
            name="attachment",
        ),
        migrations.CreateModel(
            name="BugReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="bug_reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bug_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.bugreport",
                    ),
                ),
            ],
        ),
    ]
