# Generated by Django 4.2.23 on 2026-01-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
